version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "odomatic-usa"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zq5o9qqv04d6"
s3_prefix = "odomatic-usa"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
